In [2]:
# Import All necessary Libraries numpy,pandas,matplotlib and seaborn.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [5]:
# Set up jupyter notebook options to work.
from IPython.display import display, HTML
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [6]:
# If necessary use the set options of the display . If not required. disable 
pd.set_option('display.max_columns', 70)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 1000)
pd.options.display.max_rows = 999

In [9]:
#Change the float format for display in notebook
pd.options.display.float_format = '{:,.2f}'.format

In [7]:
loan = pd.read_csv("c:/users/134466/desktop/EDA-Assignment/loan.csv")

In [11]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Columns: 111 entries, id to total_il_high_credit_limit
dtypes: float64(74), int64(13), object(24)
memory usage: 33.6+ MB

In [13]:
loan.describe()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,total_acc,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_amnt,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,...,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,"39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","14,035.00","2,786.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,717.00","39,661.00",0.00,"39,717.00",0.00,0.00,0.00,"39,717.00",0.00,0.00,...,0.00,0.00,"39,661.00","39,717.00",0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,"39,020.00","39,678.00",0.00,0.00,0.00,0.00
mean,"683,131.91","850,463.56","11,219.44","10,947.71","10,397.45",324.56,"68,968.93",13.32,0.15,0.87,35.90,69.70,9.29,0.06,"13,382.53",22.09,51.23,50.99,"12,153.60","11,567.15","9,793.35","2,263.66",1.36,95.22,12.41,"2,678.83",0.00,nan,1.00,nan,nan,nan,0.00,nan,nan,...,nan,nan,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.04,0.00,nan,nan,nan,nan
std,"210,694.13","265,678.31","7,456.67","7,187.24","7,128.45",208.87,"63,793.77",6.68,0.49,1.07,22.02,43.82,4.40,0.24,"15,885.02",11.40,375.17,373.82,"9,042.04","8,942.67","7,065.52","2,608.11",7.29,688.74,148.67,"4,447.14",0.00,nan,0.00,nan,nan,nan,0.00,nan,nan,...,nan,nan,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.20,0.00,nan,nan,nan,nan
min,"54,734.00","70,699.00",500.00,500.00,0.00,15.69,"4,000.00",0.00,0.00,0.00,0.00,0.00,2.00,0.00,0.00,2.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,nan,1.00,nan,nan,nan,0.00,nan,nan,...,nan,nan,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.00,0.00,nan,nan,nan,nan
25%,"516,221.00","666,780.00","5,500.00","5,400.00","5,000.00",167.02,"40,404.00",8.17,0.00,0.00,18.00,22.00,6.00,0.00,"3,703.00",13.00,0.00,0.00,"5,576.93","5,112.31","4,600.00",662.18,0.00,0.00,0.00,218.68,0.00,nan,1.00,nan,nan,nan,0.00,nan,nan,...,nan,nan,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.00,0.00,nan,nan,nan,nan
50%,"665,665.00","850,812.00","10,000.00","9,600.00","8,975.00",280.22,"59,000.00",13.40,0.00,1.00,34.00,90.00,9.00,0.00,"8,850.00",20.00,0.00,0.00,"9,899.64","9,287.15","8,000.00","1,348.91",0.00,0.00,0.00,546.14,0.00,nan,1.00,nan,nan,nan,0.00,nan,nan,...,nan,nan,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.00,0.00,nan,nan,nan,nan
75%,"837,755.00","1,047,339.00","15,000.00","15,000.00","14,400.00",430.78,"82,300.00",18.60,0.00,1.00,52.00,104.00,12.00,0.00,"17,058.00",29.00,0.00,0.00,"16,534.43","15,798.81","13,653.26","2,833.40",0.00,0.00,0.00,"3,293.16",0.00,nan,1.00,nan,nan,nan,0.00,nan,nan,...,nan,nan,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,0.00,0.00,nan,nan,nan,nan
max,"1,077,501.00","1,314,167.00","35,000.00","35,000.00","35,000.00","1,305.19","6,000,000.00",29.99,11.00,8.00,120.00,129.00,44.00,4.00,"149,588.00",90.00,"6,311.47","6,307.37","58,563.68","58,563.68","35,000.02","23,563.68",180.20,"29,623.35","7,002.19","36,115.20",0.00,nan,1.00,nan,nan,nan,0.00,nan,nan,...,nan,nan,0.00,0.00,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,2.00,0.00,nan,nan,nan,nan

In [15]:
loan.shape

(39717, 111)

In [18]:
loan.isnull().all()

id                                False
member_id                         False
loan_amnt                         False
funded_amnt                       False
funded_amnt_inv                   False
term                              False
int_rate                          False
installment                       False
grade                             False
sub_grade                         False
emp_title                         False
emp_length                        False
home_ownership                    False
annual_inc                        False
verification_status               False
issue_d                           False
loan_status                       False
pymnt_plan                        False
url                               False
desc                              False
purpose                           False
title                             False
zip_code                          False
addr_state                        False
dti                               False
delinq_2yrs                       False
earliest_cr_line                  False
inq_last_6mths                    False
mths_since_last_delinq            False
mths_since_last_record            False
open_acc                          False
pub_rec                           False
revol_bal                         False
revol_util                        False
total_acc                         False
initial_list_status               False
out_prncp                         False
out_prncp_inv                     False
total_pymnt                       False
total_pymnt_inv                   False
total_rec_prncp                   False
total_rec_int                     False
total_rec_late_fee                False
recoveries                        False
collection_recovery_fee           False
last_pymnt_d                      False
last_pymnt_amnt                   False
next_pymnt_d                      False
last_credit_pull_d                False
collections_12_mths_ex_med        False
mths_since_last_major_derog        True
policy_code                       False
application_type                  False
annual_inc_joint                   True
dti_joint                          True
verification_status_joint          True
acc_now_delinq                    False
tot_coll_amt                       True
tot_cur_bal                        True
open_acc_6m                        True
open_il_6m                         True
open_il_12m                        True
open_il_24m                        True
mths_since_rcnt_il                 True
total_bal_il                       True
il_util                            True
open_rv_12m                        True
open_rv_24m                        True
max_bal_bc                         True
all_util                           True
total_rev_hi_lim                   True
inq_fi                             True
total_cu_tl                        True
inq_last_12m                       True
acc_open_past_24mths               True
avg_cur_bal                        True
bc_open_to_buy                     True
bc_util                            True
chargeoff_within_12_mths          False
delinq_amnt                       False
mo_sin_old_il_acct                 True
mo_sin_old_rev_tl_op               True
mo_sin_rcnt_rev_tl_op              True
mo_sin_rcnt_tl                     True
mort_acc                           True
mths_since_recent_bc               True
mths_since_recent_bc_dlq           True
mths_since_recent_inq              True
mths_since_recent_revol_delinq     True
num_accts_ever_120_pd              True
num_actv_bc_tl                     True
num_actv_rev_tl                    True
num_bc_sats                        True
num_bc_tl                          True
num_il_tl                          True
num_op_rev_tl                      True
num_rev_accts                      True
num_rev_tl_bal_gt_0                True
num_sats                           True
num_tl_120dpd_2m                   True
num_tl_30dpd                       True
num_tl_90g_dpd_24m                 True
num_tl_op_past_12m                 True
pct_tl_nvr_dlq                     True
percent_bc_gt_75                   True
pub_rec_bankruptcies              False
tax_liens                         False
tot_hi_cred_lim                    True
total_bal_ex_mort                  True
total_bc_limit                     True
total_il_high_credit_limit         True
dtype: bool

In [28]:
null_collumn = loan.columns[loan.isnull().all()]
loan[null_collumn].isnull().sum().count()

54

In [29]:
loan.dropna(axis=1,how='all',inplace=True)

In [31]:
loan.shape

(39717, 57)

In [34]:
100*(loan.isnull().sum())/len(loan.id)>10

id                            False
member_id                     False
loan_amnt                     False
funded_amnt                   False
funded_amnt_inv               False
term                          False
int_rate                      False
installment                   False
grade                         False
sub_grade                     False
emp_title                     False
emp_length                    False
home_ownership                False
annual_inc                    False
verification_status           False
issue_d                       False
loan_status                   False
pymnt_plan                    False
url                           False
desc                           True
purpose                       False
title                         False
zip_code                      False
addr_state                    False
dti                           False
delinq_2yrs                   False
earliest_cr_line              False
inq_last_6mths                False
mths_since_last_delinq         True
mths_since_last_record         True
open_acc                      False
pub_rec                       False
revol_bal                     False
revol_util                    False
total_acc                     False
initial_list_status           False
out_prncp                     False
out_prncp_inv                 False
total_pymnt                   False
total_pymnt_inv               False
total_rec_prncp               False
total_rec_int                 False
total_rec_late_fee            False
recoveries                    False
collection_recovery_fee       False
last_pymnt_d                  False
last_pymnt_amnt               False
next_pymnt_d                   True
last_credit_pull_d            False
collections_12_mths_ex_med    False
policy_code                   False
application_type              False
acc_now_delinq                False
chargeoff_within_12_mths      False
delinq_amnt                   False
pub_rec_bankruptcies          False
tax_liens                     False
dtype: bool

In [37]:
loan.duplicated().sum()

0